 name: CI Pipeline


 on:
   push:
     branches:
       - main
   pull_request:
     branches:
       - main


 jobs:
   build:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout into the repository
         uses: actions/checkout@v4
       - working-directory: ./path-to-your-subdirectory
       - name: Install dependencies
         run: npm install
       - name: Run tests
         run: npm test
       - name: Install Dependencies
       
         
